---
- hosts: TestServerGroup
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: name=python-pip state=present

    - name: Install docker-py package
      pip: name=docker-py

    - name: Copy Dockerfile to remote host
      copy:
        src: Dockerfile
        dest: $HOME/Dockerfile
        remote_src: no

    - name: Copy html file to remote host
      copy:
        src: simple_html_page.html
        dest: $HOME/simple_html_page.html
        remote_src: no

    - name: Stop and prune current Docker containers to free port 80
      shell: |
        docker stop $(docker ps -a -q)
        docker system prune -f

    - name: Build Docker image from Dockerfile
      command: docker build -t html-server-image:v1 -f $HOME/Dockerfile .

    - name: deploy nginx server
      command: docker run -d -p 80:80 html-server-image:v1



